### PR TITLE
Added User-List

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
I'm leaving the button-color up to you :)

If you want anything changed, just address it :+1: 

img

### CODE REVIEW

**Comment by pdaddyo** [comment]
@JohnnyCrazy Please can you copy your css changes into /resouces/scss/main.scss so they can compile into the .min.css - thanks!

**Comment by pdaddyo** [comment]
@JohnnyCrazy I've pulled out your css changes into scss now, don't worry about that last request. Will tweak the UI a little before this goes live - the profile buttons don't work for FB logins, and the large button is a bit big so will refine and push live in next few days.  Thanks again!

**Comment by noafro1991** [comment]
This looks awesome!!!

**Comment by pdaddyo** [comment]
OK that's now live - without the profile button for now because it doesn't work with FB spotify logins.  https://db.tt/BHg3YEYO  Thanks agains Mr Crazy

**Pull request merged**
