### PR TITLE
Fix artist list comma color

### PR DESCRIPTION
**Pull request by mreinhardt**
Thanks for leaving in a layup issue to get me started.

This should work but I wasn't able to run the node server locally because I wasn't sure what should go in the `config = require('./config')` file as I couldn't find any checked in example files. If you could point me in the right direction to set that up so I can run the server next time that would be great.

### CODE REVIEW

**Comment by mreinhardt** [comment]
Fixes #203

**Comment by andrewthecoder** [comment]
Great work, thanks! 

A template for the server config for can be found here to get you started: https://github.com/pdaddyo/soundbounce/issues/228#issuecomment-93723898

**Comment by mreinhardt** [comment]
Sweet! Thanks @andrewthecoder 

Maybe that sample config should be put in the repository as `src/server/config.js.example`... what do you think?

**Comment by pdaddyo** [comment]
Yeah agreed it should be added to repo, thanks for fix too.

**Pull request merged**
